FROM almalinux:9
RUN mkdir /tmp/hello
# RUN cd /tmp/hello
WORKDIR /tmp/hello
RUN pwd
RUN echo "hello docker" > hello.txt

CMD ["sleep", "1000"]

# FROM almalinux:9
# RUN mkdir /tmp/hello
# # RUN cd /tmp/hello
# WORKDIR /tmp/hello
# RUN pwd
# RUN echo "hello docker" > hello.txt
# RUN useradd user1
# USER user1
# CMD ["sleep", "1000"]