FROM almalinux:9
ENV COURSE="Devops" \
    duration="120hours"
ARG trainer="sivakumar"
ARG trainee="nithin"
RUN echo "hi, iam learning course:${COURSE} of ${duration} from ${trainer}"
CMD ["sleep", "1000"]