FROM almalinux:9
RUN dnf install git -y
RUN useradd nithin
USER nithin
CMD ["google.com"]
ENTRYPOINT ["ping"]


# FROM almalinux:9
# RUN dnf install nginx -y
# # RUN useradd nithin
# # USER nithin
# CMD ["nginx", "-g", "daemon off;"]
